### ISSUE TITLE
Reinstallation clears `stripe_customer_id` attribute

### ISSUE THREAD

**Issue by aWuttig** [VIISON/ShopwareStripePayment#43]
https://github.com/VIISON/ShopwareStripePayment/blob/3d7b15d6194cb9d26c1ef27ead0fb6514612de30/Bootstrap.php#L180

When we are doing

`console sw:plugin:reinstall StripePayment `

all stripe customer ids getting removed from the s_user_attrributes table, which is because the update step 1.1.1 gets triggered and this sets all ids to NULL. This works against the secure uninstall concept of shopware --> https://developers.shopware.com/developers-guide/shopware-5-plugin-update-guide/#how-to-'secureuninstall'

I think it is a not a good idea to put update and install stuff together in one method - could you please split it up into two methods which respects the --secure / --removeData flag.

**Comment by svenmuennich** [comment]
Thanks for the bug report. This indeed breaks the reinstallation of the plugin.  Usually all installation `case`s should be idempotent themselves, but this one is not. Since `v1.1.1` has been released for a long time, we should probably merge it (and other, old migrations) into the initial `install` step.

That said, having one `update()` method and sequentially executing all migrations as needed is the method we successfully use in all our plugins. This also works with Shopware's _secure uninstall_.

**Comment by aWuttig** [comment]
ok. when do you think you you merge the 1.1.1 step into initial install step?
